clearvars
clc

%Load the image dataset
load('Combined_extracted_wells.mat');

%%
%Test image: 1 and 5 seem to be good examples
nImage = 1;

I = collImgs{nImage, 1};
Icrop = I(collStart{nImage, 1}:end, :);  %Crop to pipette tip generated by Joel's code

%% Work
close all
[Mpipette, Ipipette] = identifyPipette(Icrop);
imshow(Ipipette, [])


%%

%Run this iteratively and save results
sizes = [2, 4, 8, 10, 16, 20, 30, 40, 80, 100];

accum = zeros(size(Ipipette));

for ii = 1:numel(sizes)
    spotMask = detectSpots(Ipipette, Mpipette, sizes(ii), -5, 1);
    accum = accum + spotMask;
end

imshow(accum, []);

mask = imbinarize(accum);

imshow(mask)